### ISSUE TITLE
Failure to build zookeeper gem's native extension on linux-aarch64

### ISSUE THREAD

**Issue by patcable** [zk-ruby/zookeeper#104]
Out of the box, the zkc extension won't build on arm64/aarch64 hosts. The error I get is:
```
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2005-07-08, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.
```

Replacing the config.guess and config.sub files from the URLs mentioned solved the problem and I could compile the native library.

At one point I remember v1.4.11 not building at all on arm64 even after replacing `config.{guess,sub}` but it seems like that must have been fixed in a patch for 1.5.0. The error I got was the same one mentioned in [ZOOKEEPER-1374](https://issues.apache.org/jira/browse/ZOOKEEPER-1374).

**Comment by malmckay** [comment]
This is fixed in #105
