### ISSUE TITLE
Zookeeper.new blows up if any host cannot be resolved

### ISSUE THREAD

**Issue by mrgordon** [zk-ruby/zookeeper#21]
If I pass multiple hosts to Zookeeper.new, then I get an exception if any of the hosts cannot be resolved. However, I connect successfully if the hosts do not have Zookeeper but I can resolve them. Finally, I get failures when connecting to unreachable hosts that can be resolved when they are remote (which is what I would expect) but I get back a Zookeeper::Client object if I connect to non-existent Zookeepers on localhost.

For example, if I have Zookeeper running on localhost:2181

`Zookeeper.new('localhost:2181,a:2181')`
=> `RuntimeError: error connecting to zookeeper: 2`

`Zookeeper.new('localhost:2181,google.com:2181')`
=> `#<Zookeeper::Client:0x1106c3228 @host="localhost:2181,google.com:2181"...>`

`Zookeeper.new("localhost:1,localhost:2")`
=> `#<Zookeeper::Client:0x110d73578 @host="localhost:1,localhost:2"...>`

I'm not sure if this is intended behavior but it caught me by surprise.

**Comment by felixb** [comment]
Is there any progress on this issue?

**Comment by slyphon** [comment]
won't fix, sorry.
