### ISSUE TITLE
Make failed for zkc while linking

### ISSUE THREAD

**Issue by ullrichp** [zk-ruby/zookeeper#60]
On my system `gem install zookeeper` fails with:
```bash
linking shared-object zookeeper_c.so
/home/ullrich/.gem/ruby/1.9.1/gems/zookeeper-1.4.8/ext/lib/libzookeeper_st_gem.a(hashtable.o): In function `create_hashtable':
/home/ullrich/.gem/ruby/1.9.1/gems/zookeeper-1.4.8/ext/zkc-3.4.5/c/src/hashtable/hashtable.c:51: undefined reference to `ceilf'
/home/ullrich/.gem/ruby/1.9.1/gems/zookeeper-1.4.8/ext/lib/libzookeeper_st_gem.a(hashtable.o): In function `hashtable_expand':
/home/ullrich/.gem/ruby/1.9.1/gems/zookeeper-1.4.8/ext/zkc-3.4.5/c/src/hashtable/hashtable.c:124: undefined reference to `ceilf'
collect2: ld returned 1 exit status
make: *** [zookeeper_c.so] Error 1
```

I was able to get it compiling by hand when changing the order for the linker to have `-lm` **after** `-lzookeeper_st_gem` in the Makefile.

I am unsure what can be broken here. Any Ideas?

**Comment by mashoodfarooqi** [comment]
I am having the same issue while installing zookeeper in order to use appscale on RPi 2. i thonk its because of the missing dependencies as u can see here
checking dependency style of gcc... none
checking dependency style of g++... none

can any one help me?

**Comment by slyphon** [comment]
i have no idea what appscale or RPi2 is, but you need gcc or g++ to build the gem when it's installed
