### ISSUE TITLE
Broken on ruby-2.2.0 because of deprecated rb_thread_select

### ISSUE THREAD

**Issue by fbernier** [zk-ruby/zookeeper#72]
It builds but breaks when using it. Eventmachine had to deal with this too and fixed it with this PR: https://github.com/eventmachine/eventmachine/pull/503

**Comment by fbernier** [comment]
It looks like rb_thread_fd_select is ruby1.9.2+. Does this library still want to support 1.8?

**Comment by eric** [comment]
Yes, I still want to support ruby 1.8.

**Comment by eric** [comment]
Because I am still using it in places and I haven't seen the pain of continuing to supporting it to be very large.

**Comment by slyphon** [comment]
@korczis rumor has it a certain popular social network still uses 1.8.7 in production #JustSayin
