### ISSUE TITLE
Publish java version to rubygems

### ISSUE THREAD

**Issue by WheresAlice** [zk-ruby/zookeeper#77]
In order to get the zk gem working with jruby I had to build the java version of this zookeeper gem myself and then upload it to our local gem server (using `gem build zookeeper.gemspec`)

If you were to build and publish zookeeper-1.4.11-java.gem to the rubygems.org server then this step would not be necessary (assuming one has internet access when installing ruby gems)

**Comment by slyphon** [comment]
Um, I'm not sure why you had to build it yourself, I publish both the zookeeper and zookeeper-java gems as part of the release. I just tried to build and push it again, and got the following error:

```
jsimms@weasel:~/zookeeper   (master)   {ruby-1.9.3-p545}
[20151022-00.44.30]$ env JAVA_GEM=1  gem build zookeeper.gemspec
WARNING:  licenses is empty, but is recommended.  Use a license abbreviation from:
http://opensource.org/licenses/alphabetical
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: zookeeper
  Version: 1.4.11
  File: zookeeper-1.4.11-java.gem
jsimms@weasel:~/zookeeper   (master)   {ruby-1.9.3-p545}
[20151022-00.44.34]$ gem push zookeeper-1.4.11-java.gem
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```

My original target was jruby, so I'm pretty sure this setup works (I haven't modified it in ages).

**Comment by WheresAlice** [comment]
Huh, that's weird - I'm unable to reproduce this on my work machine.  Maybe there's a weird setup on my laptop at home, I'll close this ticket then.
