### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by timsutton** [zk-ruby/zookeeper#94]
It seems like the 1.4.11 release was done in September, 2015, but there have been a few minor fixes merged into master, https://github.com/zk-ruby/zookeeper/pull/86 and https://github.com/zk-ruby/zookeeper/pull/82 for example. With the latter I was able to build this gem on an M1 Apple Silicon Mac. Would it be possible to cut a new release for supporting installing on new Mac hardware?

**Comment by timsutton** [comment]
Just wanted to bump this if anyone with maintainership would agree on doing a new gem releases, so that this gem can be installed on Apple Silicon CPUs.

**Comment by timsutton** [comment]
Just another friendly bump on this issue, if there's any maintainer who might be able to cut a new release?

**Comment by slyphon** [comment]
Hey, I'm now talking with someone who may be able to contribute as a maintainer and cut releases etc. I haven't touched the code in 6 years, and I'm not sure I could even cut a release now. I'm hoping that we can cut a new release soon as several people are interested in these patches. I'll try to keep this ticket updated as things progress.

**Comment by malmckay** [comment]
Thanks for the push! We've released [v1.15.0](https://github.com/zk-ruby/zookeeper/releases/tag/release%2F1.5.0) which adds support for GCC 8 and ARM
